[connections.mysql]

url = "mysql://u317157586_cc_asg:$:XPL7VrH6@srv1100.hstgr.io/u317157586_cc_asg"
dialect = "mysql"
host = "srv1100.hstgr.io"
port = 3306
database="u317157586_cc_asg"
user = "u317157586_cc_asg"
password = "$:XPL7VrH6"



