[connections.mysql]
url = "mysql://root:Omm%40ir510219900@127.0.0.1/cloud_assignment"
dialect = "mysql"
host = "localhost"
port = 3306
database="cloud_assignment"
user = "root"
password = "Omm@ir510219900"